# Generated by Django 4.2.1 on 2023-05-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(verbose_name='Data do agendamento')),
                ('issue', models.CharField(max_length=200)),
                ('is_checked', models.BooleanField()),
            ],
        ),
    ]
